### ISSUE TITLE
Change "DefaultApi" to "AriaddnaApi"

### ISSUE THREAD

**Issue by kosmoflyko** [StnetixDevTeam/ariADDna#40]
Can we change "DefaultApi" to "AriaddnaApi"? I think the customer will be easier make and remember Api object consist in the name target to connection, for ex. AriaddnaApi, GoogleDriveApi, ...

**Comment by vasap87** [comment]
I think we can wrap DefaultApi. If we rename DefaultApi class, we should rename it every regeneration client.
