### ISSUE TITLE
Make store service for collected SSL certificate

### ISSUE THREAD

**Issue by kosmoflyko** [StnetixDevTeam/ariADDna#50]
M9-1: Service should be make CRUID operation with SSL certificate into JKS file.

**Comment by vasap87** [comment]
#74

**Comment by vasap87** [comment]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] ariaddna-platform .................................. SUCCESS [  0.341 s]
[INFO] rest-api-server .................................... SUCCESS [  6.201 s]
[INFO] common-utils ....................................... SUCCESS [  0.980 s]
[INFO] desktop-gui ........................................ SUCCESS [  0.409 s]
[INFO] desktop-core ....................................... SUCCESS [  0.086 s]
[INFO] rest-api-client .................................... SUCCESS [  2.006 s]
[INFO] storage-service .................................... SUCCESS [ 10.386 s]
[INFO] keystore-service ................................... SUCCESS [  9.141 s]
[INFO] server-core ........................................ SUCCESS [ 10.556 s]
[INFO] local-storage-manager .............................. SUCCESS [  0.564 s]
[INFO] notify-server ...................................... SUCCESS [  7.886 s]
[INFO] rest-api-cloud-client .............................. SUCCESS [  0.225 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 49.050 s
[INFO] Finished at: 2017-07-11T12:25:42+03:00
[INFO] Final Memory: 54M/606M
[INFO] ------------------------------------------------------------------------
