### ISSUE TITLE
Make Storage manager modul for support keystore

### ISSUE THREAD

**Issue by kosmoflyko** [StnetixDevTeam/ariADDna#60]
Storage manager contain next package:
1. entity - POJO classes for represent domain model for persist in DB.
2. repository - interfaces for all entity objects.
3. services - interfaces and implementation service for get, find and persist entity object. 
4. dto - serializable JavaBeans classes for represent domain model and contain bulder for simple constract.
5. transformers - service classes use MapStruct library for convert DTO to Entity and vice versa
6. utils - classes for helping connect to DB and read JPA configuration files (persist.xml)

Any modules should be send/recieve only DTO classes. For example abstract workflow for persist some abstract User: UserService.persist(dto.User) -> TransformationUtil.convertToEntity(dto.User) -> UserRepository.persist(entity.User)

See simple examle [Spring JPA](http://spring-projects.ru/guides/accessing-data-jpa/) (in this example Application implementing service functionality)

See MapStruct [documentation ](http://mapstruct.org/documentation/dev/reference/html/)and [quick guide](http://www.baeldung.com/mapstruct)

See documentetion on [Storage Manager](https://github.com/StnetixDevTeam/ariADDna/wiki/Storage-Manager)

**Comment by vasap87** [comment]
https://github.com/StnetixDevTeam/ariADDna/pull/69
