### ISSUE TITLE
Notify Server module build is FAILED

### ISSUE THREAD

**Issue by kosmoflyko** [StnetixDevTeam/ariADDna#72]
ERROR LOG:
------------------------------
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.stnetix.ariaddna:notify-server:war:1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ com.stnetix.ariaddna:ariaddna-platform:1.0-SNAPSHOT, C:\Users\Vladislav Gasanov\IdeaProjects\ariADDna\pom.xml, line 13, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building notify-server 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ notify-server ---
[INFO] Deleting C:\Users\Vladislav Gasanov\IdeaProjects\ariADDna\notify-server\target
[INFO]
[INFO] --- build-helper-maven-plugin:1.9.1:add-source (add-source) @ notify-server ---
[INFO] Source directory: C:\Users\Vladislav Gasanov\IdeaProjects\ariADDna\notify-server\src\gen\java added.
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ notify-server ---
[WARNING] Using platform encoding (Cp1251 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Users\Vladislav Gasanov\IdeaProjects\ariADDna\notify-server\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ notify-server ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding Cp1251, i.e. build is platform dependent!
[INFO] Compiling 32 source files to C:\Users\Vladislav Gasanov\IdeaProjects\ariADDna\notify-server\target\classes
[WARNING] /C:/Users/Vladislav Gasanov/IdeaProjects/ariADDna/notify-server/src/main/java/com/stnetix/ariaddna/pushnotification/client/AutoConnectSocket.java: Some input files use unchecked or unsafe operations.
[WARNING] /C:/Users/Vladislav Gasanov/IdeaProjects/ariADDna/notify-server/src/main/java/com/stnetix/ariaddna/pushnotification/client/AutoConnectSocket.java: Recompile with -Xlint:unchecked for details.
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ notify-server ---
[WARNING] Using platform encoding (Cp1251 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Users\Vladislav Gasanov\IdeaProjects\ariADDna\notify-server\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ notify-server ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ notify-server ---
[INFO] No tests to run.
[INFO]
[INFO] --- maven-war-plugin:2.1.1:war (default-war) @ notify-server ---
[INFO] Packaging webapp
[INFO] Assembling webapp [notify-server] in [C:\Users\Vladislav Gasanov\IdeaProjects\ariADDna\notify-server\target\notify-server-1.0-SNAPSHOT]
[INFO] Processing war project
[INFO] Webapp assembled in [355 msecs]
[INFO] Building war: C:\Users\Vladislav Gasanov\IdeaProjects\ariADDna\notify-server\target\notify-server-1.0-SNAPSHOT.war
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.129 s
[INFO] Finished at: 2017-06-17T21:14:08+03:00
[INFO] Final Memory: 21M/189M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-war-plugin:2.1.1:war (default-war) on project notify-server: Error assembling WAR: webxml attribute is required (or pre-existing WEB-INF/web.xml if executing in update mode) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by vasap87** [comment]
To fix it you have to modify pom.xml in module.

```xml
<plugin>
   <groupId>org.apache.maven.plugins</groupId>
   <artifactId>maven-war-plugin</artifactId>
    <version>2.1.1</version>
      <configuration> <!--Added Kotov Alexandr to build-->
         <webXml>src/webapp/WEB-INF/web.xml.back</webXml>
      </configuration>
</plugin>
```
