### ISSUE TITLE
storage-service module run TESTs is FAILED

### ISSUE THREAD

**Issue by kosmoflyko** [StnetixDevTeam/ariADDna#73]
When I run "mvn clean install" for this module build is failed, but without tests is success.

Project module haven't README file now. And customer can't read right way for build this module. 

ERROR LOG:
------------------------------
Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2017-06-17 21:20:52.350 ERROR 1772 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'appConfiguration': Unsatisfied dependency expressed through field 'em'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'entityManager' defined in class path resource [com/stnetix/ariaddna/persistence/utils/JPAConfiguration.class]: Unsatisfied dependency expressed through method 'entityManager' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [com/stnetix/ariaddna/persistence/utils/JPAConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.persistence.EntityManagerFactory]: Factory method 'entityManagerFactory' threw exception; nested exception is java.lang.IllegalArgumentException: DataSource must not be null
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:588) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]

**Comment by vasap87** [comment]
#74

**Comment by kosmoflyko** [comment]
fix #81
